PREFIX ont: <http://purl.org/net/ns/ontology-annot#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX onto: <http://www.banderasazulesgalicia.com/ontologia#>

SELECT  DISTINCT ?playa ?lat ?lon ?ta ?tp ?nu ?na ?ca ?np ?Links ?cp ?lp ?mi
WHERE {
  ?playa a <http://www.banderasazulesgalicia.com/ontologia#playa>;
  <http://www.banderasazulesgalicia.com/ontologia#latitud> ?lat;
  <http://www.banderasazulesgalicia.com/ontologia#longitud> ?lon;
  <http://www.banderasazulesgalicia.com/ontologia#tipoArena> ?ta, "Gruesa";
  <http://www.banderasazulesgalicia.com/ontologia#tipoPlaya> ?tp;
  <http://www.banderasazulesgalicia.com/ontologia#NombreUbicacion> ?nu;
  <http://www.banderasazulesgalicia.com/ontologia#NombreAyuntamiento> ?na;
  <http://www.banderasazulesgalicia.com/ontologia#codigoAyuntamiento> ?ca;
  <http://www.banderasazulesgalicia.com/ontologia#NombreProvincia> ?np, "A Coruña Province";
  <http://www.w3.org/2002/07/owl#sameAs> ?Links;
  <http://www.banderasazulesgalicia.com/ontologia#codigoProvincia> ?cp;
  <http://www.banderasazulesgalicia.com/ontologia#longitudPlaya> ?lp;
  <http://www.banderasazulesgalicia.com/ontologia#masInfo> ?mi;
}